### PR TITLE
Craft 5 support

### PR DESCRIPTION
**Pull request by likeabas**

### CODE REVIEW

**Review by nstcactus — APPROVED** [review]

**Comment by nstcactus** [comment]
Thank you for your PR.

I no longer work at La Haute Société so I'm no longer the one maintaining tjia but I'm sure someone at @lhs-dev can have a look.

**Comment by likeabas** [comment]
@nstCactus thanks for checking it anyway! @lhs-dev could you have a look and merge 👀

**Comment by mathieu-coingt** [comment]
Hey @likeabas , sorry for the delay.
Your MR was approved.
Thank you.

**Comment by GeoFeij** [comment]
Hi @lhs-dev, would it be possible to create a release with the craft 5 support? Thanks in advance!

**Comment by likeabas** [comment]
@mathieu-coingt @lhs-dev thanks for the merge! A new release in Craft can be done simply by creating a new release tag

**Comment by likeabas** [comment]
@mathieu-coingt @lhs-dev  Can you please add the release tag as well? Now people still can't update

**Comment by mathieu-coingt** [comment]
It's done @likeabas.
Really sorry for the delay.
Thank you for your involvement ❤️

**Pull request merged**
